@startuml

abstract class AbstractList
abstract AbstractCollection
interface List
interface Collection

List <|-- AbstractList
Collection <.. AbstractCollection

Collection <|-- List
AbstractCollection <--> AbstractList
AbstractList *--- ArrayList
Person o--> JiaJie

class ArrayList {
    Object[] elementData
    size()
}

class Person {
    String name
    int age
}

class JiaJie {

}

enum TimeUnit {
    DAYS
    HOURS
    MINUTES
}

@enduml